

CREATE TABLE IF NOT EXISTS companys
               (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL,
               show_name TEXT, owner TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users
               (u_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               username TEXT NOT NULL, email TEXT NOT NULL,
               hash TEXT NOT NULL, role TEXT NOT NULL, FOREIGN KEY (c_id)
               REFERENCES companys (id) ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS vehicles
               (v_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               make TEXT NOT NULL, model TEXT NOT NULL,
               year TEXT NOT NULL, number TEXT NOT NULL, vin TEXT UNIQUE NOT NULL,
               tag TEXT, FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
               ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS inspections
                (i_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
                u_id INTEGER NOT NULL, v_id INTEGER NOT NULL, miles INTEGER NOT NULL,
                next_oil INTEGER NOT NULL, next_1 INTEGER, next_2 INTEGER, date TEXT NOT NULL,
                first_name TEXT, last_name TEXT,
                borsa_documenti INTEGER, borsa_documenti_t TEXT, borsa_documenti_b BLOB,
                blocchetto_viaggio INTEGER, blocchetto_viaggio_t TEXT, blocchetto_viaggio_b BLOB,
                tariffario INTEGER, tariffario_t TEXT, tariffario_b BLOB,
                scheda_carburante INTEGER, scheda_carburante_t TEXT, scheda_carburante_b BLOB,
                schede_118 INTEGER, schede_118_t TEXT, schede_118_b BLOB,
                carlina INTEGER, carlina_t TEXT, carlina_b BLOB,
                navigatore INTEGER, navigatore_t TEXT, navigatore_b BLOB,
                carta_circola_fotocopia INTEGER, carta_circola_fotocopia_t TEXT, carta_circola_fotocopia_b BLOB,
                cartello_fuori_servizio INTEGER, cartello_fuori_servizio_t TEXT, cartello_fuori_servizio_b BLOB,
                elenco_dotazione_ambulanza INTEGER, elenco_dotazione_ambulanza_t TEXT, elenco_dotazione_ambulanza_b BLOB,
                tagliando_assicurazione INTEGER, tagliando_assicurazione_t TEXT, tagliando_assicurazione_b BLOB,
                cert_idoneita_asl_fotocopia INTEGER, cert_idoneita_asl_fotocopia_t TEXT, cert_idoneita_asl_fotocopia_b BLOB,
                giubbotto_alta_visibilita INTEGER, giubbotto_alta_visibilita_t TEXT, giubbotto_alta_visibilita_b BLOB,
                triangolo INTEGER, triangolo_t TEXT, triangolo_b BLOB,
                estintore_cabina INTEGER, estintore_cabina_t TEXT, estintore_cabina_b BLOB,
                torcia INTEGER, torcia_t TEXT, torcia_b BLOB,
                guanti_da_lavoro INTEGER, guanti_da_lavoro_t TEXT, guanti_da_lavoro_b BLOB,
                cassetta_porta_attrezzi INTEGER, cassetta_porta_attrezzi_t TEXT, cassetta_porta_attrezzi_b BLOB,
                gel_battericida_lavamani INTEGER, gel_battericida_lavamani_t TEXT, gel_battericida_lavamani_b BLOB,
                taglia_s INTEGER, taglia_s_t TEXT, taglia_s_b BLOB,
                taglia_m INTEGER, taglia_m_t TEXT, taglia_m_b BLOB,
                taglia_l INTEGER, taglia_l_t TEXT, taglia_l_b BLOB,
                taglia_xl INTEGER, taglia_xl_t TEXT, taglia_xl_b BLOB,
                cassetti INTEGER, cassetti_t TEXT, cassetti_b BLOB,
                forbici_garze INTEGER, forbici_garze_t TEXT, forbici_garze_b BLOB,
                garze_non_sterili_10x10 INTEGER, garze_non_sterili_10x10_t TEXT, garze_non_sterili_10x10_b BLOB,
                garze_non_sterili_30x30 INTEGER, garze_non_sterili_30x30_t TEXT, garze_non_sterili_30x30_b BLOB,
                garze_sterili INTEGER, garze_sterili_t TEXT, garze_sterili_b BLOB,
                rasoio INTEGER, rasoio_t TEXT, rasoio_b BLOB
                laccio_emostatico_lea INTEGER, laccio_emostatico_lea_t TEXT, laccio_emostatico_lea_b BLOB,
                tellino_sterile INTEGER, tellino_sterile_t TEXT, tellino_sterile_b BLOB,
                nastrotela INTEGER, nastrotela_t TEXT, nastrotela_b BLOB,
                cerotti_medicati_scatola INTEGER, cerotti_medicati_scatola_t TEXT, cerotti_medicati_scatola_b BLOB,
                bende_orlate_medie INTEGER, bende_orlate_medie_t TEXT, bende_orlate_medie_b BLOB,
                bende_orlate_grandi INTEGER, bende_orlate_grandi_t TEXT, bende_orlate_grandi_b BLOB,
                benda_auto_adesiva_grande INTEGER, benda_auto_adesiva_grande_t TEXT, benda_auto_adesiva_grande_b BLOB,
                benda_auto_adesiva_piccola INTEGER, benda_auto_adesiva_piccola_t TEXT, benda_auto_adesiva_piccola_b BLOB,
                disinfettante_cutaneo INTEGER, disinfettante_cutaneo_t TEXT, disinfettante_cutaneo_b BLOB,
                acqua_ossigenata INTEGER, acqua_ossigenata_t TEXT, acqua_ossigenata_b BLOB,
                ghiaccio_istantaneo INTEGER, ghiaccio_istantaneo_t TEXT, ghiaccio_istantaneo_b BLOB,
                ghiaccio_spray INTEGER, ghiaccio_spray_t TEXT, ghiaccio_spray_b BLOB,
                coperta_isotermica INTEGER, coperta_isotermica_t TEXT, coperta_isotermica_b BLOB,
                siringhe INTEGER, siringhe_t TEXT, siringhe_b BLOB,
                cavo_12v_aspiratore INTEGER, cavo_12v_aspiratore_t TEXT, cavo_12v_aspiratore_b BLOB,
                forbici_robin INTEGER, forbici_robin_t TEXT, forbici_robin_b BLOB,
                piastre_adulto INTEGER, piastre_adulto_t TEXT, piastre_adulto_b BLOB,
                piastre_pediatriche INTEGER, piastre_pediatriche_t TEXT, piastre_pediatriche_b BLOB,
                lenzuolo_sterile INTEGER, lenzuolo_sterile_t TEXT, lenzuolo_sterile_b BLOB,
                rasoio_monouso INTEGER, rasoio_monouso_t TEXT, rasoio_monouso_b BLOB,
                manuale_istruzioni INTEGER, manuale_istruzioni_t TEXT, manuale_istruzioni_b BLOB,
                aspiratore_fisso INTEGER, aspiratore_fisso_t TEXT, aspiratore_fisso_b BLOB,
                aspiratore_portatile INTEGER, aspiratore_portatile_t TEXT, aspiratore_portatile_b BLOB,
                sacchetti_scorta INTEGER, sacchetti_scorta_t TEXT, sacchetti_scorta_b BLOB,
                ventilatore_polmonare INTEGER, ventilatore_polmonare_t TEXT, ventilatore_polmonare_b BLOB,
                frigorifero INTEGER, frigorifero_t TEXT, frigorifero_b BLOB,
                collari_diverse_misure INTEGER, collari_diverse_misure_t TEXT, collari_diverse_misure_b BLOB,
                barella_principale INTEGER, barella_principale_t TEXT, barella_principale_b BLOB,
                coperta INTEGER, coperta_t TEXT, coperta_b BLOB,
                barella_atraumatica INTEGER, barella_atraumatica_t TEXT, barella_atraumatica_b BLOB,
                cinghie_cucchiaio INTEGER, cinghie_cucchiaio_t TEXT, cinghie_cucchiaio_b BLOB,
                telo_portafetiti INTEGER, telo_portafetiti_t TEXT, telo_portafetiti_b BLOB,
                set_infettivi INTEGER, set_infettivi_t TEXT, set_infettivi_b BLOB,
                ked INTEGER, ked_t TEXT, ked_b BLOB,
                sedia_portantina INTEGER, sedia_portantina_t TEXT, sedia_portantina_b BLOB,
                elmetto_antine_occhiali INTEGER, elmetto_antine_occhiali_t TEXT, elmetto_antine_occhiali_b BLOB,
                occhiali_protettivi INTEGER, occhiali_protettivi_t TEXT, occhiali_protettivi_b BLOB,
                mascherine_chirurgiche INTEGER, mascherine_chirurgiche_t TEXT, mascherine_chirurgiche_b BLOB,
                estintore_2kg INTEGER, estintore_2kg_t TEXT, estintore_2kg_b BLOB,
                multipresa_mobile INTEGER, multipresa_mobile_t TEXT, multipresa_mobile_b BLOB,
                bombolino_o2_vista INTEGER, bombolino_o2_vista_t TEXT, bombolino_o2_vista_b BLOB,
                rilevatore_monossido INTEGER, rilevatore_monossido_t TEXT, rilevatore_monossido_b BLOB,
                asse_spinale_adulti INTEGER, asse_spinale_adulti_t TEXT, asse_spinale_adulti_b BLOB,
                asse_spinale INTEGER, asse_spinale_t TEXT, asse_spinale_b BLOB,
                base_fermacapo INTEGER, base_fermacapo_t TEXT, base_fermacapo_b BLOB,
                cuscini_fermacapo INTEGER, cuscini_fermacapo_t TEXT, cuscini_fermacapo_b BLOB,
                ragno INTEGER, ragno_t TEXT, ragno_b BLOB,
                cinghie_fermacapo INTEGER, cinghie_fermacapo_t TEXT, cinghie_fermacapo_b BLOB,
                asse_spinale_pediatrica INTEGER, asse_spinale_pediatrica_t TEXT, asse_spinale_pediatrica_b BLOB,
                steccobende_piccola INTEGER, steccobende_piccola_t TEXT, steccobende_piccola_b BLOB,
                steccobende_media INTEGER, steccobende_media_t TEXT, steccobende_media_b BLOB,
                steccobende_grande INTEGER, steccobende_grande_t TEXT, steccobende_grande_b BLOB,
                sondino_nero_ch10 INTEGER, sondino_nero_ch10_t TEXT, sondino_nero_ch10_b BLOB,
                sondino_bianco_ch12 INTEGER, sondino_bianco_ch12_t TEXT, sondino_bianco_ch12_b BLOB,
                sondino_verde_ch14 INTEGER, sondino_verde_ch14_t TEXT, sondino_verde_ch14_b BLOB,
                sondino_arancio_ch16 INTEGER, sondino_arancio_ch16_t TEXT, sondino_arancio_ch16_b BLOB,
                sondino_rosso_ch18 INTEGER, sondino_rosso_ch18_t TEXT, sondino_rosso_ch18_b BLOB,
                sondino_giallo_ch20 INTEGER, sondino_giallo_ch20_t TEXT, sondino_giallo_ch20_b BLOB,
                maschera_ossigeno_adulto_reservoir INTEGER, maschera_ossigeno_adulto_reservoir_t TEXT, maschera_ossigeno_adulto_reservoir_b BLOB,
                maschera_ossigeno_adulto_senza_reservoir INTEGER, maschera_ossigeno_adulto_senza_reservoir_t TEXT, maschera_ossigeno_adulto_senza_reservoir_b BLOB,
                maschera_ossigeno_pediatrico_reservoir INTEGER, maschera_ossigeno_pediatrico_reservoir_t TEXT, maschera_ossigeno_pediatrico_reservoir_b BLOB,
                maschera_ossigeno_pediatrico_senza_reservoir INTEGER, maschera_ossigeno_pediatrico_senza_reservoir_t TEXT, maschera_ossigeno_pediatrico_senza_reservoir_b BLOB,
                tubo_raccordo_o2 INTEGER, tubo_raccordo_o2_t TEXT, tubo_raccordo_o2_b BLOB,
                occhialini_o2 INTEGER, occhialini_o2_t TEXT, occhialini_o2_b BLOB,
                padella INTEGER, padella_t TEXT, padella_b BLOB,
                pappagallo INTEGER, pappagallo_t TEXT, pappagallo_b BLOB,
                bacinella INTEGER, bacinella_t TEXT, bacinella_b BLOB,
                spruzzino_disinfettante INTEGER, spruzzino_disinfettante_t TEXT, spruzzino_disinfettante_b BLOB,
                carta INTEGER, carta_t TEXT, carta_b BLOB,
                contenitore_taglienti INTEGER, contenitore_taglienti_t TEXT, contenitore_taglienti_b BLOB,
                sacchetti_rifiuti INTEGER, sacchetti_rifiuti_t TEXT, sacchetti_rifiuti_b BLOB,
                telli_sterili INTEGER, telli_sterili_t TEXT, telli_sterili_b BLOB,
                clamp INTEGER, clamp_t TEXT, clamp_b BLOB,
                metalline_baby INTEGER, metalline_baby_t TEXT, metalline_baby_b BLOB,
                metallina_adulti INTEGER, metallina_adulti_t TEXT, metallina_adulti_b BLOB,
                aspiramico INTEGER, aspiramico_t TEXT, aspiramico_b BLOB,
                sonda_saturimetro_pediatrico INTEGER, sonda_saturimetro_pediatrico_t TEXT, sonda_saturimetro_pediatrico_b BLOB,
                sonda_saturimetro_neonatale INTEGER, sonda_saturimetro_neonatale_t TEXT, sonda_saturimetro_neonatale_b BLOB,
                batteria_di_scorta INTEGER, batteria_di_scorta_t TEXT, batteria_di_scorta_b BLOB,
                fonendo_baby INTEGER, fonendo_baby_t TEXT, fonendo_baby_b BLOB,
                bracciale_pressione INTEGER, bracciale_pressione_t TEXT, bracciale_pressione_b BLOB,
                sfigmomanometro_baby INTEGER, sfigmomanometro_baby_t TEXT, sfigmomanometro_baby_b BLOB,
                pallone_ambu INTEGER, pallone_ambu_t TEXT, pallone_ambu_b BLOB,
                reservoir_per_ambu INTEGER, reservoir_per_ambu_t TEXT, reservoir_per_ambu_b BLOB,
                filtro_per_ambu INTEGER, filtro_per_ambu_t TEXT, filtro_per_ambu_b BLOB,
                tubo_raccordo_o2_per_ambu INTEGER, tubo_raccordo_o2_per_ambu_t TEXT, tubo_raccordo_o2_per_ambu_b BLOB,
                maschera_piccola_per_ambu INTEGER, maschera_piccola_per_ambu_t TEXT, maschera_piccola_per_ambu_b BLOB,
                cannula_guedel_bianca_1 INTEGER, cannula_guedel_bianca_1_t TEXT, cannula_guedel_bianca_1_b BLOB,
                cannula_guedel_nera_0 INTEGER, cannula_guedel_nera_0_t TEXT, cannula_guedel_nera_0_b BLOB,
                cannula_guedel_blu_00 INTEGER, cannula_guedel_blu_00_t TEXT, cannula_guedel_blu_00_b BLOB,
                cannula_guedel_rosa_000 INTEGER, cannula_guedel_rosa_000_t TEXT, cannula_guedel_rosa_000_b BLOB,
                siringa_singola INTEGER, siringa_singola_t TEXT, siringa_singola_b BLOB,
                frusta_principale INTEGER, frusta_principale_t TEXT, frusta_principale_b BLOB,
                frusta_derivazioni INTEGER, frusta_derivazioni_t TEXT, frusta_derivazioni_b BLOB,
                saturimetro_monitor INTEGER, saturimetro_monitor_t TEXT, saturimetro_monitor_b BLOB,
                cavo_test INTEGER, cavo_test_t TEXT, cavo_test_b BLOB,
                elettrodi INTEGER, elettrodi_t TEXT, elettrodi_b BLOB,
                piastre_monitor INTEGER, piastre_monitor_t TEXT, piastre_monitor_b BLOB,
                elettrodi_di_scorta INTEGER, elettrodi_di_scorta_t TEXT, elettrodi_di_scorta_b BLOB,
                carta_scorta INTEGER, carta_scorta_t TEXT, carta_scorta_b BLOB,
                gel_monitor INTEGER, gel_monitor_t TEXT, gel_monitor_b BLOB,
                set_arti INTEGER, set_arti_t TEXT, set_arti_b BLOB,
                sacco_mano INTEGER, sacco_mano_t TEXT, sacco_mano_b BLOB,
                sacca_braccio INTEGER, sacca_braccio_t TEXT, sacca_braccio_b BLOB,
                sacca_gamba INTEGER, sacca_gamba_t TEXT, sacca_gamba_b BLOB,
                ghiaccio_sterile INTEGER, ghiaccio_sterile_t TEXT, ghiaccio_sterile_b BLOB,
                garze_30x30 INTEGER, garze_30x30_t TEXT, garze_30x30_b BLOB,
                cerotti INTEGER, cerotti_t TEXT, cerotti_b BLOB,
                benda_tela INTEGER, benda_tela_t TEXT, benda_tela_b BLOB,
                telo_sterile_allumin_60x80 INTEGER, telo_sterile_allumin_60x80_t TEXT, telo_sterile_allumin_60x80_b BLOB,
                metalline INTEGER, metalline_t TEXT, metalline_b BLOB,
                fisiologiche_da_infusione INTEGER, fisiologiche_da_infusione_t TEXT, fisiologiche_da_infusione_b BLOB,
                fisiologiche_da_lavaggio INTEGER, fisiologiche_da_lavaggio_t TEXT, fisiologiche_da_lavaggio_b BLOB,
                sacchetto_vomito INTEGER, sacchetto_vomito_t TEXT, sacchetto_vomito_b BLOB,
                teli_barella INTEGER, teli_barella_t TEXT, teli_barella_b BLOB,
                traversa_monouso INTEGER, traversa_monouso_t TEXT, traversa_monouso_b BLOB,
                sacca_medicazione_verde INTEGER, sacca_medicazione_verde_t TEXT, sacca_medicazione_verde_b BLOB,
                nastro_carta INTEGER, nastro_carta_t TEXT, nastro_carta_b BLOB,
                nastro_telato INTEGER, nastro_telato_t TEXT, nastro_telato_b BLOB,
                guanti_sterili INTEGER, guanti_sterili_t TEXT, guanti_sterili_b BLOB,
                cerotti_in_scatola_medicati INTEGER, cerotti_in_scatola_medicati_t TEXT, cerotti_in_scatola_medicati_b BLOB,
                forbici_piccole INTEGER, forbici_piccole_t TEXT, forbici_piccole_b BLOB,
                pallone_ambu_adulto INTEGER, pallone_ambu_adulto_t TEXT, pallone_ambu_adulto_b BLOB,
                reservoir_per_ambu_adulto INTEGER, reservoir_per_ambu_adulto_t TEXT, reservoir_per_ambu_adulto_b BLOB,
                filtro_per_ambu_adulto INTEGER, filtro_per_ambu_adulto_t TEXT, filtro_per_ambu_adulto_b BLOB,
                tubo_raccordo_o2_per_ambu_adulto INTEGER, tubo_raccordo_o2_per_ambu_adulto_t TEXT, tubo_raccordo_o2_per_ambu_adulto_b BLOB,
                maschera_piccola_per_ambu_adulto INTEGER, maschera_piccola_per_ambu_adulto_t TEXT, maschera_piccola_per_ambu_adulto_b BLOB,
                maschera_media_per_ambu_adulto INTEGER, maschera_media_per_ambu_adulto_t TEXT, maschera_media_per_ambu_adulto_b BLOB,
                maschera_grande_per_ambu_adulto INTEGER, maschera_grande_per_ambu_adulto_t TEXT, maschera_grande_per_ambu_adulto_b BLOB,
                maschera_con_reservoir_o2 INTEGER, maschera_con_reservoir_o2_t TEXT, maschera_con_reservoir_o2_b BLOB,
                cannula_guedel_bianca_1_adulto INTEGER, cannula_guedel_bianca_1_adulto_t TEXT, cannula_guedel_bianca_1_adulto_b BLOB,
                cannula_guedel_gialla_2 INTEGER, cannula_guedel_gialla_2_t TEXT, cannula_guedel_gialla_2_b BLOB,
                cannula_guedel_verde_3 INTEGER, cannula_guedel_verde_3_t TEXT, cannula_guedel_verde_3_b BLOB,
                cannula_guedel_arancio_4 INTEGER, cannula_guedel_arancio_4_t TEXT, cannula_guedel_arancio_4_b BLOB,
                cannula_guedel_azzurra_5 INTEGER, cannula_guedel_azzurra_5_t TEXT, cannula_guedel_azzurra_5_b BLOB,
                termometro INTEGER, termometro_t TEXT, termometro_b BLOB,
                fonendo INTEGER, fonendo_t TEXT, fonendo_b BLOB,
                bracciale_pressione_monitor INTEGER, bracciale_pressione_monitor_t TEXT, bracciale_pressione_monitor_b BLOB,
                sfigmomanometro INTEGER, sfigmomanometro_t TEXT, sfigmomanometro_b BLOB,
                fonendoscopio INTEGER, fonendoscopio_t TEXT, fonendoscopio_b BLOB,
                batterie_di_scorta INTEGER, batterie_di_scorta_t TEXT, batterie_di_scorta_b BLOB,
                sondino_bianco_ch12 INTEGER, sondino_bianco_ch12_t TEXT, sondino_bianco_ch12_b BLOB,
                sondino_verde_ch14 INTEGER, sondino_verde_ch14_t TEXT, sondino_verde_ch14_b BLOB,
                sondino_arancio_ch16 INTEGER, sondino_arancio_ch16_t TEXT, sondino_arancio_ch16_b BLOB,
                sondino_rosso_ch18 INTEGER, sondino_rosso_ch18_t TEXT, sondino_rosso_ch18_b BLOB,
                sondino_giallo_ch20 INTEGER, sondino_giallo_ch20_t TEXT, sondino_giallo_ch20_b BLOB,
                set_scasso INTEGER, set_scasso_t TEXT, set_scasso_b BLOB,
                badile INTEGER, badile_t TEXT, badile_b BLOB,
                catene_da_neve INTEGER, catene_da_neve_t TEXT, catene_da_neve_b BLOB,
                bombolino_o2_di_scorta INTEGER, bombolino_o2_di_scorta_t TEXT,
                FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
                ON UPDATE NO ACTION, FOREIGN KEY (u_id) REFERENCES users (u_id) ON DELETE NO ACTION
                ON UPDATE NO ACTION, FOREIGN KEY (v_id) REFERENCES vehicles (v_id) ON DELETE CASCADE
                ON UPDATE NO ACTION);