

CREATE TABLE IF NOT EXISTS companys
               (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL,
               show_name TEXT, owner TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users
               (u_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               username TEXT NOT NULL, email TEXT NOT NULL,
               hash TEXT NOT NULL, role TEXT NOT NULL,
FOREIGN KEY (c_id)
               REFERENCES companys (id) ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS vehicles
               (v_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
               make TEXT NOT NULL, model TEXT NOT NULL,
               year TEXT NOT NULL, number TEXT NOT NULL, vin TEXT UNIQUE NOT NULL,
               tag TEXT, FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
               ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS inspections
                (i_id INTEGER PRIMARY KEY, c_id INTEGER NOT NULL,
                u_id INTEGER NOT NULL, v_id INTEGER NOT NULL, miles INTEGER NOT NULL,
                next_oil INTEGER NOT NULL, next_1 INTEGER, next_2 INTEGER, date TEXT NOT NULL,
                first_name TEXT, last_name TEXT,
                danni_alla_carrozzeria INTEGER, danni_alla_carrozzeria_t TEXT, danni_alla_carrozzeria_b BLOB,
                danni_alla_tappezzeria INTEGER, danni_alla_tappezzeria_t TEXT, danni_alla_tappezzeria_b BLOB,
                stato_degli_pneumatici INTEGER, stato_degli_pneumatici_t TEXT, stato_degli_pneumatici_b BLOB,
                controllo_pulizia_interna_esterna INTEGER, controllo_pulizia_interna_esterna_t TEXT, controllo_pulizia_interna_esterna_b BLOB,
                prova_dispositivi_di_segnalazione_ottici_ed_acustici INTEGER, prova_dispositivi_di_segnalazione_ottici_ed_acustici_t TEXT, prova_dispositivi_di_segnalazione_ottici_ed_acustici_b BLOB,
                controllo_efficienza_apparato_radio INTEGER, controllo_efficienza_apparato_radio_t TEXT, controllo_efficienza_apparato_radio_b BLOB,
                prova_efficienza_tergicristallo INTEGER, prova_efficienza_tergicristallo_t TEXT, prova_efficienza_tergicristallo_b BLOB,
                prova_efficienza_condizionatore INTEGER, prova_efficienza_condizionatore_t TEXT, prova_efficienza_condizionatore_b BLOB,
                tagliando INTEGER, tagliando_t TEXT, tagliando_b BLOB,
                assicurazione INTEGER, assicurazione_t TEXT, assicurazione_b BLOB,
                carta_di_circolazione INTEGER, carta_di_circolazione_t TEXT, carta_di_circolazione_b BLOB,
                modulistica_di_servizio INTEGER, modulistica_di_servizio_t TEXT, modulistica_di_servizio_b BLOB,
                estintori INTEGER, estintori_t TEXT, estintori_b BLOB,
                ruota_di_scorta INTEGER, ruota_di_scorta_t TEXT, ruota_di_scorta_b BLOB,
                triangolo INTEGER, triangolo_t TEXT, triangolo_b BLOB,
                torce_a_vento INTEGER, torce_a_vento_t TEXT, torce_a_vento_b BLOB,
                fari_di_illuminazione INTEGER, fari_di_illuminazione_t TEXT, fari_di_illuminazione_b BLOB,
                giubbino_alta_visibilità INTEGER, giubbino_alta_visibilità_t TEXT, giubbino_alta_visibilità_b BLOB,
                olio_motore INTEGER, olio_motore_t TEXT, olio_motore_b BLOB,
                liquido_di_raffreddamento INTEGER, liquido_di_raffreddamento_t TEXT, liquido_di_raffreddamento_b BLOB,
                liquido_freni INTEGER, liquido_freni_t TEXT, liquido_freni_b BLOB,
                liquido_servosterzo INTEGER, liquido_servosterzo_t TEXT, liquido_servosterzo_b BLOB,
                liquido_tergicristalli INTEGER, liquido_tergicristalli_t TEXT, liquido_tergicristalli_b BLOB,
                controllo_generale INTEGER, controllo_generale_t TEXT, controllo_generale_b BLOB,
                impianto_ossigeno INTEGER, impianto_ossigeno_t TEXT, impianto_ossigeno_b BLOB,
                bombole_ossigeno INTEGER, bombole_ossigeno_t TEXT, bombole_ossigeno_b BLOB,
                impianto_elettrico INTEGER, impianto_elettrico_t TEXT, impianto_elettrico_b BLOB,
                impianto_aspirazione INTEGER, impianto_aspirazione_t TEXT, impianto_aspirazione_b BLOB,
                condizionatore_vano_sanitario INTEGER, condizionatore_vano_sanitario_t TEXT, condizionatore_vano_sanitario_b BLOB,
                barella_automatica INTEGER, barella_automatica_t TEXT, barella_automatica_b BLOB,
                barella_atraumatica INTEGER, barella_atraumatica_t TEXT, barella_atraumatica_b BLOB,
                traslatore_barella INTEGER, traslatore_barella_t TEXT, traslatore_barella_b BLOB,
                attrezzature_elettromedicali INTEGER, attrezzature_elettromedicali_t TEXT, attrezzature_elettromedicali_b BLOB,
                defibrillatore INTEGER, defibrillatore_t TEXT, defibrillatore_b BLOB,
                pulsossimetro INTEGER, pulsossimetro_t TEXT, pulsossimetro_b BLOB,
                dispositivi_di_immobilizzazione INTEGER, dispositivi_di_immobilizzazione_t TEXT, dispositivi_di_immobilizzazione_b BLOB,
                sedili INTEGER, sedili_t TEXT, sedili_b BLOB,
                mobiletti_rak_portaflebo INTEGER, mobiletti_rak_portaflebo_t TEXT, mobiletti_rak_portaflebo_b BLOB,
                maschere_resevoir_adulto INTEGER, maschere_resevoir_adulto_t TEXT, maschere_resevoir_adulto_b BLOB,
                maschere_resevoir_pediatrico INTEGER, maschere_resevoir_pediatrico_t TEXT, maschere_resevoir_pediatrico_b BLOB,
                maschere_bassi_flussi_adulto INTEGER, maschere_bassi_flussi_adulto_t TEXT, maschere_bassi_flussi_adulto_b BLOB,
                maschere_bassi_flussi_ped INTEGER, maschere_bassi_flussi_ped_t TEXT, maschere_bassi_flussi_ped_b BLOB,
                canule_nasali_o2 INTEGER, canule_nasali_o2_t TEXT, canule_nasali_o2_b BLOB,
                bombole_fisse_cariche INTEGER, bombole_fisse_cariche_t TEXT, bombole_fisse_cariche_b BLOB,
                bombolini_sacca_res INTEGER, bombolini_sacca_res_t TEXT, bombolini_sacca_res_b BLOB,
                fisiologiche_lavaggio INTEGER, fisiologiche_lavaggio_t TEXT, fisiologiche_lavaggio_b BLOB,
                cerotti_qb INTEGER, cerotti_qb_t TEXT, cerotti_qb_b BLOB,
                garza_autoadesiva INTEGER, garza_autoadesiva_t TEXT, garza_autoadesiva_b BLOB,
                cerotto_carta_seta INTEGER, cerotto_carta_seta_t TEXT, cerotto_carta_seta_b BLOB,
                bende_qb INTEGER, bende_qb_t TEXT, bende_qb_b BLOB,
                compresse_garza_sterile INTEGER, compresse_garza_sterile_t TEXT, compresse_garza_sterile_b BLOB,
                ghiaccio INTEGER, ghiaccio_t TEXT, ghiaccio_b BLOB,
                ghiaccio_spray INTEGER, ghiaccio_spray_t TEXT, ghiaccio_spray_b BLOB,
                acqua_ossigenata INTEGER, acqua_ossigenata_t TEXT, acqua_ossigenata_b BLOB,
                disinfettante_cute_lesa INTEGER, disinfettante_cute_lesa_t TEXT, disinfettante_cute_lesa_b BLOB,
                forbici_garza INTEGER, forbici_garza_t TEXT, forbici_garza_b BLOB,
                forbici_robin INTEGER, forbici_robin_t TEXT, forbici_robin_b BLOB,
                sondini_aspiratore_calibro INTEGER, sondini_aspiratore_calibro_t TEXT, sondini_aspiratore_calibro_b BLOB,
                teli_barella INTEGER, teli_barella_t TEXT, teli_barella_b BLOB,
                panno_carta INTEGER, panno_carta_t TEXT, panno_carta_b BLOB,
                traversine INTEGER, traversine_t TEXT, traversine_b TEXT,
                bacinella INTEGER, bacinella_t TEXT, bacinella_b BLOB,
                pappagallo INTEGER, pappagallo_t TEXT, pappagallo_b BLOB,
                alcool_denat INTEGER, alcool_denat_t TEXT, alcool_denat_b BLOB,
                disinfettante_superfici INTEGER, disinfettante_superfici_t TEXT, disinfettante_superfici_b BLOB,
                tute_infettivi_complete INTEGER, tute_infettivi_complete_t TEXT, tute_infettivi_complete_b BLOB,
                guanti_s INTEGER, guanti_s_t TEXT, guanti_s_b BLOB,
                guanti_m INTEGER, guanti_m_t TEXT, guanti_m_b BLOB,
                guanti_l INTEGER, guanti_l_t TEXT, guanti_l_b BLOB,
                guanti_xl INTEGER, guanti_xl_t TEXT, guanti_xl_b BLOB,
                dae_piastre INTEGER, dae_piastre_t TEXT, dae_piastre_b BLOB,
                monitor_multiparametrico INTEGER, monitor_multiparametrico_t TEXT, monitor_multiparametrico_b BLOB,
                aspiratore_fisso INTEGER, aspiratore_fisso_t TEXT, aspiratore_fisso_b BLOB,
                aspiratore_portatile INTEGER, aspiratore_portatile_t TEXT, aspiratore_portatile_b BLOB,
                ked INTEGER, ked_t TEXT, ked_b BLOB,
                steccobende INTEGER, steccobende_t TEXT, steccobende_b BLOB,
                kit_ustioni INTEGER, kit_ustioni_t TEXT, kit_ustioni_b BLOB,
                kit_reimpianto_arti INTEGER, kit_reimpianto_arti_t TEXT, kit_reimpianto_arti_b BLOB,
                pedimed INTEGER, pedimed_t TEXT, pedimed_b BLOB,
                barella INTEGER, barella_t TEXT, barella_b BLOB,
                telo INTEGER, telo_t TEXT, telo_b BLOB,
                asse_spinale_ragno INTEGER, asse_spinale_ragno_t TEXT, asse_spinale_ragno_b BLOB,
                cucchiaio_scoop_cinghie INTEGER, cucchiaio_scoop_cinghie_t TEXT, cucchiaio_scoop_cinghie_b BLOB,
                collari INTEGER, collari_t TEXT, collari_b BLOB,
                fissatori_capo INTEGER, fissatori_capo_t TEXT, fissatori_capo_b BLOB,
                kit_scasso INTEGER, kit_scasso_t TEXT, kit_scasso_b BLOB,
                sacca_parametri INTEGER, sacca_parametri_t TEXT, sacca_parametri_b BLOB,
                sacca_medicazioni INTEGER, sacca_medicazioni_t TEXT, sacca_medicazioni_b BLOB,
                sacca_rianimazione INTEGER, sacca_rianimazione_t TEXT, sacca_rianimazione_b BLOB,
                sacca_sondini_aspiratore INTEGER, sacca_sondini_aspiratore_t TEXT, sacca_sondini_aspiratore_b BLOB,
                robin INTEGER, robin_t TEXT, robin_b BLOB,
                sacchetti_spazzatura INTEGER, sacchetti_spazzatura_t TEXT, sacchetti_spazzatura_b BLOB,
                metalline INTEGER, metalline_t TEXT, metalline_b BLOB,
                sacca_parametri_ped INTEGER, sacca_parametri_ped_t TEXT, sacca_parametri_ped_b BLOB,
                sacca_rianimazione_ped INTEGER, sacca_rianimazione_ped_t TEXT, sacca_rianimazione_ped_b BLOB,
                kit_parto INTEGER, kit_parto_t TEXT, kit_parto_b BLOB,
                metallina INTEGER, metallina_t TEXT, metallina_b BLOB,
                maschere_ossigenoterapia_ped INTEGER, maschere_ossigenoterapia_ped_t TEXT, maschere_ossigenoterapia_ped_b BLOB,
                FOREIGN KEY (c_id) REFERENCES companys (id) ON DELETE CASCADE
                ON UPDATE NO ACTION, FOREIGN KEY (u_id) REFERENCES users (u_id) ON DELETE NO ACTION
                ON UPDATE NO ACTION, FOREIGN KEY (v_id) REFERENCES vehicles (v_id) ON DELETE CASCADE
                ON UPDATE NO ACTION);